# Set generator variables
path: search.json
field: post
format: html
limit: 10000
content: true
# Set theme layout
layout:
  # If auto, trigger search by changing input.
  # If manual, trigger search by pressing enter key or search button.
  trigger: auto
  # Show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # Unescape html strings to the readable one.
  unescape: false
  # Preload the search data when the page loads.
  preload: false
menu:
  icon: fas fa-search
  priority: 20
